routes/web.php
	Route::get('site/{page}', 'WebsiteController@site');
	Route::post('contact/send_message', 'WebsiteController@send_message');
	Route::match(['get', 'post'], '/login_refeed', 'UserController@refeed');
	Auth::routes(['verify' => true]);
	Route::get('/faq', function () {
    return view('theme.default.faq');
    });
	


	Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
	Route::match(['get', 'post'], 'register/client_signup', '\App\Http\Controllers\Auth\RegisterController@client_signup');

	Route::group(['middleware' => ['auth', 'verified']], function () {

		Route::get('/dashboard', 'DashboardController@index');

		//Profile Controller
		Route::get('/signup_step', 'ProfileController@signup_step')->name('signup_step');
		Route::post('update_step', 'ProfileController@update_step');
		Route::get('/getcity/{id}', 'ProfileController@getCity')->name('signup_step.getCity');
        Route::get('/getsubdistrict/{id}', 'ProfileController@getSubdistrict')->name('signup_step.getSubdistrict');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::get('/getcity/{id}', 'ProfileController@getCity')->name('profile.edit.getCity');
        Route::get('/getsubdistrict/{id}', 'ProfileController@getSubdistrict')->name('profile.edit.getSubdistrict');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/change_password', 'ProfileController@change_password');
		Route::post('profile/update_password', 'ProfileController@update_password');
		Route::get('perusahaan/edit', 'CompanySettingsController@edit');
		Route::post('perusahaan/update', 'CompanySettingsController@update');

		//Membertship Controller
		Route::get('membership/my_subscription', 'MembershipController@my_subscription');  //View Subscription Details
		Route::get('membership/extend', 'MembershipController@extend');

		//Select Payment Gateway
		Route::post('membership/pay', 'MembershipController@pay');

		//Payment Gateway PayPal	
		Route::get('membership/paypal/{action?}', 'MembershipController@paypal');
		Route::get('membership/ipaymu/{action?}','MembershipController@ipaymu');

		//Payment Gateway Stripe
		Route::get('membership/stripe_payment/{action}/{payment_id?}', 'MembershipController@stripe_payment');

		//Payment Gateway RazorPay
		Route::post('membership/razorpay_payment/{payment_id}', 'MembershipController@razorpay_payment');

		//Paystack Payment Gateway
		Route::get('membership/paystack_payment/{payment_id}/{reference}', 'MembershipController@paystack_payment');


		/** Admin Only Route **/
		Route::group(['middleware' => ['admin']], function () {
			//User Controller
			Route::get('users/type/{user_type}', 'UserController@index');
			Route::resource('users', 'UserController');
			Route::get('/edit_progress/{id}','UserController@edit_progress');
			Route::post('/update_progress/{id}','UserController@update_progress');


			//Payment Controller
			Route::get('offline_payment/create', 'PaymentController@create_offline_payment');
			Route::post('offline_payment/store', 'PaymentController@store_offline_payment');
			Route::get('members/payment_history', 'PaymentController@payment_history');

			//Feature Controller
			Route::resource('features', 'FeatureController');

			//FAQ Controller
			Route::resource('faqs', 'FaqController');

			//Package Controller
			Route::resource('packages', 'PackageController');

			//Language Controller
			Route::resource('languages', 'LanguageController');

			//Utility Controller
			Route::match(['get', 'post'], 'administration/general_settings/{store?}', 'UtilityController@settings');
			Route::match(['get', 'post'], 'administration/theme_option/{store?}', 'UtilityController@theme_option');
			Route::post('administration/upload_logo', 'UtilityController@upload_logo');
			Route::match(['get', 'patch'], 'administration/currency_rates/{id?}', 'UtilityController@currency_rates');
			Route::get('administration/backup_database', 'UtilityController@backup_database');

			//Theme Option
			Route::match(['get', 'post'], 'administration/theme_option/{store?}', 'UtilityController@theme_option');

			//Email Template
			Route::resource('email_templates', 'EmailTemplateController')->only([
				'index', 'show', 'edit', 'update'
			]);
		});

		Route::group(['middleware' => ['company']], function () {


			//Project Controller
			Route::post('projects/get_table_data', 'ProjectController@get_table_data');
			Route::resource('projects', 'ProjectController');

			//Builder
			Route::resource('project/builder', 'BuilderController');
			Route::get('updateproject/builder/{id}', 'BuilderController@index');
			Route::get('project/larabuilder', 'BuilderController@larabuilder');
			Route::get('builder/novi', 'BuilderController@novi');
			Route::get('builder/lara', 'BuilderController@lara');
			Route::match(['get', 'post'], 'api/ajax', 'BuilderController@ajax');
			Route::get('test/backend/assets/builder', 'BuilderController@empty');

			//Payment Method
			Route::resource('payment_methods', 'PaymentMethodController');

			//Staff Controller
			Route::resource('staffs', 'StaffController');

			//User Roles
			Route::resource('roles', 'RoleController');

			//File Manager Controller
			Route::get('file_manager/directory/{parent_id}', 'FileManagerController@index')->name('file_manager.index');
			Route::get('file_manager/create_folder/{parent_id?}', 'FileManagerController@create_folder')->name('file_manager.create_folder');
			Route::post('file_manager/store_folder', 'FileManagerController@store_folder')->name('file_manager.create_folder');
			Route::get('file_manager/edit_folder/{id}', 'FileManagerController@edit_folder')->name('file_manager.edit_folder');
			Route::patch('file_manager/update_folder/{id}', 'FileManagerController@update_folder')->name('file_manager.edit_folder');
			Route::get('file_manager/create/{parent_id?}', 'FileManagerController@create')->name('file_manager.create');
			Route::resource('file_manager', 'FileManagerController');


			//Company Settings Controller
			Route::post('company/upload_logo', 'CompanySettingsController@upload_logo')->name('company.change_logo');
			Route::match(['get', 'post'], 'company/general_settings/{store?}', 'CompanySettingsController@settings')->name('company.change_settings');

			Route::match(['get', 'post'], 'company/crm_settings', 'CompanySettingsController@crm_settings')->name('company.crm_settings');

			//Company Email Template
			Route::get('company_email_template/get_template/{id}', 'CompanyEmailTemplateController@get_template');
			Route::resource('company_email_template', 'CompanyEmailTemplateController');

			//Permission Controller
			Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.manage');
			Route::post('permission/store', 'PermissionController@store')->name('permission.manage');
		});

		Route::group(['middleware' => ['client']], function () {

			//Projects
			Route::get('client/projects', 'ClientController@projects');
			Route::get('client/projects/{id}', 'ClientController@view_project');
		});
	});

	//Subdomains
	$domain = '{subdomain}.' . parse_url(config('app.url'), PHP_URL_HOST);
	Route::domain($domain)->group(function () {
		Route::get('/index.html', function ($subdomain) {
			$p = \App\Project::where('custom_domain', $subdomain)->first();
			abort_if(is_null($p), '404');
			return File::get(public_path() . '/sites/' . $p->user_id . '/' . $p->id . '/index.html');
		});
	});


	//Convert Currency
	Route::get('convert_currency/{from}/{to}/{amount}', 'AccountController@convert_currency');

	//Get Client Info
	Route::get('contacts/get_client_info/{id}', 'ContactController@get_client_info');

	//Get Client Info
	Route::get('projects/get_project_info/{id}', 'ProjectController@get_project_info');

	//View Invoice & Quotation without login
	Route::get('client/view_invoice/{id}', 'ClientController@view_invoice');

	//Online Invoice Payment
	Route::get('client/invoice_payment/{id}/{payment_method}', 'ClientController@invoice_payment');

	//Stripe Payment Gateway
	Route::get('client/stripe_payment/{action}/{invoice_id}', 'ClientController@stripe_payment');

	//PayPal Payment Gateway
	Route::get('client/paypal/{action?}/{invoice_id?}', 'ClientController@paypal');
	Route::get('client/ipaymu/{action?}/{invoice_id?}','ClientController@ipaymu');	

	//Payment Gateway RazorPay
	Route::post('client/razorpay_payment/{invoice_id}', 'ClientController@razorpay_payment');

	//Paystack Payment Gateway
	Route::get('client/paystack_payment/{invoice_id}/{reference}', 'ClientController@paystack_payment');

	//Invoice & Quotation PDF Download
	Route::get('invoices/download_pdf/{id}', 'ClientController@download_invoice_pdf');
// });

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

//Ajax Select2 Controller
Route::get('ajax/get_table_data', 'Select2Controller@get_table_data');

Route::post('createProject', 'ApiController@createProject');
Route::post('updateProject/{id}', 'ApiController@updateProject');

//Show Notification
Route::get('notification/{id}', 'NotificationController@show')->middleware('auth');

//Google Login
Route::get('google/redirect', 'Auth\SocialAuthGoogleController@redirect');
Route::get('google/callback', 'Auth\SocialAuthGoogleController@callback');

//Update System
Route::get('migration/update', 'Install\UpdateController@update_migration');

//PayPal IPN for Membership Payment
Route::post('membership/paypal_ipn', 'MembershipController@paypal_ipn');

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Image;
use App\Utilities\Translator;

class LanguageController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.administration.language.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('backend.administration.language.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		@ini_set('max_execution_time', 0);
		@set_time_limit(0);
		
        $this->validate($request, [
            'language_name' => 'required|alpha|string|max:30',
            //'flag' => 'required|image|dimensions:min_width=64,min_height=42',
        ]);
		
		$name = $request->language_name;
		$direction = $request->language_direction;
		
		if(file_exists(resource_path() . "/language/$name.php")){
			return redirect()->back()->with('error',_lang('Language already exists !'));
		}
		
		$language = file_get_contents(resource_path() . "/language/language.php");
		$language = str_replace('$language["SYSDIRECTIONDIR"] = "ltr";', '$language["SYSDIRECTIONDIR"] = "'.$direction.'";', $language);
		$new_file = fopen(resource_path() . "/language/$name.php",'w+');
		fwrite($new_file,$language);
		fclose($new_file);
        
		//Store Flag image
		if ($request->hasFile('flag')){
            $image = $request->file('flag');
            $file_name = $name.'.'.$image->getClientOriginalExtension();
            Image::make($image)->crop(24,24)->save(base_path('public/uploads/flags/') .$file_name);
        }
		
		return redirect('languages')->with('success',_lang('Language Created Sucessfully'));
    
	}

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $name
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    { 
        if(file_exists(resource_path() . "/language/$id.php")){
			require (resource_path() . "/language/$id.php");
			
			//Find New Language key
			$language_2 = Translator::get_language_key();	
			$new_keys = array_diff_key($language_2, $language);
            
            $language = array_merge($language, $new_keys);
            
            // foreach($language as $key => $lang){
            //     echo '$language["'.$key.'"] = "'.$lang.'";';
            //     echo '<br />';
            // }
            // exit;

            
			
		    return view('backend.administration.language.edit',compact('language','id'));
		}
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {	
	    @ini_set('max_execution_time', 0);
		@set_time_limit(0);
		@ini_set('max_input_vars', 5000);
		
		$contents="<?php \n\n";
		$contents.='$language = array();'."\n\n";	  
		foreach($_POST['language'] as $key => $value){
		  $l_value = str_replace('"','',$value);
		  $contents.='$language["'.str_replace("_"," ",$key).'"] = "'.$l_value.'";'."\n";
		}
        if( @ini_get('max_input_vars') < 2000 ){
            return redirect('languages')->with('error',_lang('Error! You must need to set max_input_vars = 2000 for updating translations'));
        }else{
            $file = fopen(resource_path() . "/language/$id.php","w");
            if(fwrite($file, $contents)){
            return redirect('languages')->with('success',_lang('Updated Sucessfully'));
            }else{
            return redirect('languages')->with('success',_lang('Update failed !'));
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(file_exists(resource_path() . "/language/$id.php")){
			unlink(resource_path() . "/language/$id.php");
			return redirect('languages')->with('success',_lang('Removed Sucessfully'));
		}
    }
}

resources/views/backend/administration/language/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-4">
		<div class="card">		
			<span class="panel-title d-none">{{ _lang('Add New Language') }}</span>

			<div class="card-body">
			  <form method="post" class="validate" autocomplete="off" action="{{ url('languages') }}" enctype="multipart/form-data">
				{{ csrf_field() }}
				<div class="row">
				    <div class="col-md-12">
						<div class="form-group">
							<label class="control-label">{{ _lang('Language Name') }}</label>						
							<input type="text" class="form-control" name="language_name" value="{{ old('language_name') }}" required>
						</div>
						<div class="form-group">
							<label class="control-label">{{ _lang('Language Direction') }}</label>						
							<select class="form-control auto-select" data-selected="{{ old('language_direction','ltr') }}" name="language_direction" required>
								<option value="ltr">{{ _lang('LTR') }}</option>
								<option value="rtl">{{ _lang('RTL') }}</option>
							</select>
						</div>
						<div class="form-group">
							<label class="control-label">{{ _lang('Language Flag') }}</label>					
							<input type="file" class="form-control dropify" name="flag" data-max-file-size="2M" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" required>
						</div>
					</div>
					
					<div class="col-md-12">
						<div class="form-group">
							<button type="submit" class="btn btn-primary">{{ _lang('Create Language') }}</button>
						</div>
					</div>
				</div>
			  </form>
			</div>
	  	</div>
 	</div>
</div>
@endsection

resources/views/backend/administration/language/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="panel-title d-none">{{ _lang('Edit Translation') }}</div>

			<div class="card-body">
			  
			  @if( @ini_get('max_input_vars') < 2000 )
				<div class="alert alert-danger">
					<span>You must need to set <b>max_input_vars = 2000</b> for updating language</span>
				</div>						
			  @endif
			  
			  <form method="post" class="validate" autocomplete="off" action="{{ action('LanguageController@update', $id) }}">
				{{ csrf_field() }}
				<input name="_method" type="hidden" value="PATCH">
				<div class="row">
					@foreach($language as $key => $lang)
					@if($key == 'SYSDIRECTIONDIR' or $key == 'SYS_DIRECTION_DIR')
						<input type="hidden" class="form-control" name="language[{{ str_replace(' ','_',$key) }}]" value="{{ $lang }}" required>
						@continue
					@endif
					<div class="col-md-6">
					  <div class="form-group">
						<label class="control-label">{{ ucwords($key) }}</label>						
						<input type="text" class="form-control" name="language[{{ str_replace(' ','_',$key) }}]" value="{{ $lang }}" required>
					  </div>
					</div>
					@endforeach
					
					<div class="col-md-12">
					  <div class="form-group">
						<button type="submit" class="btn btn-primary">{{ _lang('Save Translation') }}</button>
					  </div>
					</div>
				</div>
			  </form>
			</div>
	  	</div>
 	</div>
</div>
@endsection

resources/views/backend/administration/language/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-12">
	    
		<a class="btn btn-primary btn-xs" href="{{ route('languages.create') }}"><i class="ti-plus"></i> {{ _lang('Add New') }}</a>
			
		<div class="card mt-2">
			
			<span class="panel-title d-none">{{ _lang('Languages') }}</span>
			<div class="card-body">
			 <div class="table-responsive">
				 <table class="table table-bordered">
					<thead>
					  <tr>
						<th>{{ _lang('Language Name') }}</th>
						<th>{{ _lang('Edit Translation') }}</th>
						<th>{{ _lang('Remove') }}</th>
					  </tr>
					</thead>
					<tbody>
					  
					  @foreach(get_language_list() as $language)
					  <tr>
						<td>{{ $language }}</td>
						<td>
							<a href="{{ action('LanguageController@edit', $language) }}" class="btn btn-secondary btn-xs">{{ _lang('Edit Translation') }}</a>
						</td>	
						<td>
							<form action="{{ action('LanguageController@destroy', $language) }}" method="post">
							   {{ csrf_field() }}
							   <input name="_method" type="hidden" value="DELETE">
							   <button class="btn btn-danger btn-xs btn-remove" type="submit">{{ _lang('Delete') }}</button>
							</form>
						</td>
					  </tr>
					  @endforeach
					</tbody>
				  </table>
			  </div>
			</div>
		</div>
	</div>
</div>

@endsection