routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::group(['middleware' => ['install']], function () {

	Route::get('/', 'WebsiteController@index');
	Route::get('sign_up', 'WebsiteController@sign_up');
	Route::get('site/contactus', 'WebsiteController@contactus');
	Route::get('site/{page}', 'WebsiteController@site');
	Route::post('contact/send_message', 'WebsiteController@send_message');
	Route::match(['get', 'post'], '/login_refeed', 'UserController@refeed');
	Auth::routes(['verify' => true]);
	Route::get('/faq', function () {
    return view('theme.default.faq');
    });
	


	Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
	Route::match(['get', 'post'], 'register/client_signup', '\App\Http\Controllers\Auth\RegisterController@client_signup');

	Route::group(['middleware' => ['auth', 'verified']], function () {

		Route::get('/dashboard', 'DashboardController@index');

		//Profile Controller
		Route::get('/signup_step', 'ProfileController@signup_step')->name('signup_step');
		Route::post('update_step', 'ProfileController@update_step');
		Route::get('/getcity/{id}', 'ProfileController@getCity')->name('signup_step.getCity');
        Route::get('/getsubdistrict/{id}', 'ProfileController@getSubdistrict')->name('signup_step.getSubdistrict');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::get('/getcity/{id}', 'ProfileController@getCity')->name('profile.edit.getCity');
        Route::get('/getsubdistrict/{id}', 'ProfileController@getSubdistrict')->name('profile.edit.getSubdistrict');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/change_password', 'ProfileController@change_password');
		Route::post('profile/update_password', 'ProfileController@update_password');
		Route::get('perusahaan/edit', 'CompanySettingsController@edit');
		Route::post('perusahaan/update', 'CompanySettingsController@update');

		//Membertship Controller
		Route::get('membership/my_subscription', 'MembershipController@my_subscription');  //View Subscription Details
		Route::get('membership/extend', 'MembershipController@extend');

		//Select Payment Gateway
		Route::post('membership/pay', 'MembershipController@pay');

		//Payment Gateway PayPal	
		Route::get('membership/paypal/{action?}', 'MembershipController@paypal');
		Route::get('membership/ipaymu/{action?}','MembershipController@ipaymu');

		//Payment Gateway Stripe
		Route::get('membership/stripe_payment/{action}/{payment_id?}', 'MembershipController@stripe_payment');

		//Payment Gateway RazorPay
		Route::post('membership/razorpay_payment/{payment_id}', 'MembershipController@razorpay_payment');

		//Paystack Payment Gateway
		Route::get('membership/paystack_payment/{payment_id}/{reference}', 'MembershipController@paystack_payment');


		/** Admin Only Route **/
		Route::group(['middleware' => ['admin']], function () {
			//User Controller
			Route::get('users/type/{user_type}', 'UserController@index');
			Route::resource('users', 'UserController');
			Route::get('/edit_progress/{id}','UserController@edit_progress');
			Route::post('/update_progress/{id}','UserController@update_progress');


			//Payment Controller
			Route::get('offline_payment/create', 'PaymentController@create_offline_payment');
			Route::post('offline_payment/store', 'PaymentController@store_offline_payment');
			Route::get('members/payment_history', 'PaymentController@payment_history');

			//Feature Controller
			Route::resource('features', 'FeatureController');

			//FAQ Controller
			Route::resource('faqs', 'FaqController');

			//Package Controller
			Route::resource('packages', 'PackageController');

			//Language Controller
			Route::resource('languages', 'LanguageController');

			//Utility Controller
			Route::match(['get', 'post'], 'administration/general_settings/{store?}', 'UtilityController@settings');
			Route::match(['get', 'post'], 'administration/theme_option/{store?}', 'UtilityController@theme_option');
			Route::post('administration/upload_logo', 'UtilityController@upload_logo');
			Route::match(['get', 'patch'], 'administration/currency_rates/{id?}', 'UtilityController@currency_rates');
			Route::get('administration/backup_database', 'UtilityController@backup_database');

			//Theme Option
			Route::match(['get', 'post'], 'administration/theme_option/{store?}', 'UtilityController@theme_option');

			//Email Template
			Route::resource('email_templates', 'EmailTemplateController')->only([
				'index', 'show', 'edit', 'update'
			]);
		});

		Route::group(['middleware' => ['company']], function () {


			//Project Controller
			Route::post('projects/get_table_data', 'ProjectController@get_table_data');
			Route::resource('projects', 'ProjectController');

			//Builder
			Route::resource('project/builder', 'BuilderController');
			Route::get('updateproject/builder/{id}', 'BuilderController@index');
			Route::get('project/larabuilder', 'BuilderController@larabuilder');
			Route::get('builder/novi', 'BuilderController@novi');
			Route::get('builder/lara', 'BuilderController@lara');
			Route::match(['get', 'post'], 'api/ajax', 'BuilderController@ajax');
			Route::get('test/backend/assets/builder', 'BuilderController@empty');

			//Payment Method
			Route::resource('payment_methods', 'PaymentMethodController');

			//Staff Controller
			Route::resource('staffs', 'StaffController');

			//User Roles
			Route::resource('roles', 'RoleController');

			//File Manager Controller
			Route::get('file_manager/directory/{parent_id}', 'FileManagerController@index')->name('file_manager.index');
			Route::get('file_manager/create_folder/{parent_id?}', 'FileManagerController@create_folder')->name('file_manager.create_folder');
			Route::post('file_manager/store_folder', 'FileManagerController@store_folder')->name('file_manager.create_folder');
			Route::get('file_manager/edit_folder/{id}', 'FileManagerController@edit_folder')->name('file_manager.edit_folder');
			Route::patch('file_manager/update_folder/{id}', 'FileManagerController@update_folder')->name('file_manager.edit_folder');
			Route::get('file_manager/create/{parent_id?}', 'FileManagerController@create')->name('file_manager.create');
			Route::resource('file_manager', 'FileManagerController');


			//Company Settings Controller
			Route::post('company/upload_logo', 'CompanySettingsController@upload_logo')->name('company.change_logo');
			Route::match(['get', 'post'], 'company/general_settings/{store?}', 'CompanySettingsController@settings')->name('company.change_settings');

			Route::match(['get', 'post'], 'company/crm_settings', 'CompanySettingsController@crm_settings')->name('company.crm_settings');

			//Company Email Template
			Route::get('company_email_template/get_template/{id}', 'CompanyEmailTemplateController@get_template');
			Route::resource('company_email_template', 'CompanyEmailTemplateController');

			//Permission Controller
			Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.manage');
			Route::post('permission/store', 'PermissionController@store')->name('permission.manage');
		});

		Route::group(['middleware' => ['client']], function () {

			//Projects
			Route::get('client/projects', 'ClientController@projects');
			Route::get('client/projects/{id}', 'ClientController@view_project');
		});
	});

	//Subdomains
	$domain = '{subdomain}.' . parse_url(config('app.url'), PHP_URL_HOST);
	Route::domain($domain)->group(function () {
		Route::get('/index.html', function ($subdomain) {
			$p = \App\Project::where('custom_domain', $subdomain)->first();
			abort_if(is_null($p), '404');
			return File::get(public_path() . '/sites/' . $p->user_id . '/' . $p->id . '/index.html');
		});
	});


	//Convert Currency
	Route::get('convert_currency/{from}/{to}/{amount}', 'AccountController@convert_currency');

	//Get Client Info
	Route::get('contacts/get_client_info/{id}', 'ContactController@get_client_info');

	//Get Client Info
	Route::get('projects/get_project_info/{id}', 'ProjectController@get_project_info');

	//View Invoice & Quotation without login
	Route::get('client/view_invoice/{id}', 'ClientController@view_invoice');

	//Online Invoice Payment
	Route::get('client/invoice_payment/{id}/{payment_method}', 'ClientController@invoice_payment');

	//Stripe Payment Gateway
	Route::get('client/stripe_payment/{action}/{invoice_id}', 'ClientController@stripe_payment');

	//PayPal Payment Gateway
	Route::get('client/paypal/{action?}/{invoice_id?}', 'ClientController@paypal');
	Route::get('client/ipaymu/{action?}/{invoice_id?}','ClientController@ipaymu');	

	//Payment Gateway RazorPay
	Route::post('client/razorpay_payment/{invoice_id}', 'ClientController@razorpay_payment');

	//Paystack Payment Gateway
	Route::get('client/paystack_payment/{invoice_id}/{reference}', 'ClientController@paystack_payment');

	//Invoice & Quotation PDF Download
	Route::get('invoices/download_pdf/{id}', 'ClientController@download_invoice_pdf');
// });

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

//Ajax Select2 Controller
Route::get('ajax/get_table_data', 'Select2Controller@get_table_data');

resources/views/backend/user2/modal/create.blade.php
<form method="post" class="ajax-submit" autocomplete="off" action="{{route('users.store')}}" enctype="multipart/form-data">
	{{ csrf_field() }}
	<div class="row p-2">
		<div class="col-md-12">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Business Name') }}</label>						
			<input type="text" class="form-control" name="business_name" value="{{ old('business_name') }}" required>
		  </div>
		</div>
		
		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Name') }}</label>						
			<input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
		  </div>
		</div>

		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Email') }}</label>						
			<input type="email" class="form-control" name="email" value="{{ old('email') }}">
		  </div>
		</div>

		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Password') }}</label>						
			<input type="password" class="form-control" name="password">
		  </div>
		</div>
		
		<div class="col-md-6">
		 <div class="form-group">
			<label class="control-label">{{ _lang('Confirm Password') }}</label>						
			<input type="password" class="form-control" name="password_confirmation" required>
		 </div>
		</div>
		
		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Package') }}</label>						
			<select class="form-control select2" name="package_id" required>
				<option value="">{{ _lang('Select Package') }}</option>
				{{ create_option('packages','id','package_name',old('package_id')) }}
			</select>
		  </div>
		</div>
		  
		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Package Type') }}</label>						
			<select class="form-control" id="package_type" name="package_type" required>
				<option value="">{{ _lang('Select Package') }}</option>
				<option value="monthly">{{ _lang('Monthly') }}</option>
				<option value="yearly">{{ _lang('Yearly') }}</option>
			</select>
		  </div>
		</div>

		
		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Membership Type') }}</label>						
			<select class="form-control select2" name="membership_type" id="membership_type" required>
			  <option value="trial">{{ _lang('Trial') }}</option>
			  <option value="member">{{ _lang('Member') }}</option>
			</select>
		  </div>
		</div>
		
		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Status') }}</label>						
			<select class="form-control select2" id="status" name="status" required>
			  <option value="1">{{ _lang('Active') }}</option>
			  <option value="0">{{ _lang('Inactive') }}</option>
			</select>
		  </div>
		</div>
		
		
		<div class="col-md-12">
		 <div class="form-group">
			<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>						
			<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="">
		 </div>
		</div>
					
		<div class="col-md-12">
		  <div class="form-group">
			<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
			<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
		  </div>
		</div>
	</div>
</form>

resources/views/backend/user2/modal/edit.blade.php
<form method="post" class="ajax-submit" autocomplete="off" action="{{action('UserController@update', $id)}}" enctype="multipart/form-data">
	{{ csrf_field()}}
	<input name="_method" type="hidden" value="PATCH">				
	<div class="row p-2">
		<div class="col-md-12">
		 <div class="form-group">
			<label class="control-label">{{ _lang('Business Name') }}</label>						
			<input type="text" class="form-control" name="business_name" value="{{ $user->company->business_name }}" required>
		 </div>
		</div>
		
		<div class="col-md-6">
		 <div class="form-group">
			<label class="control-label">{{ _lang('Name') }}</label>						
			<input type="text" class="form-control" name="name" value="{{ $user->name }}" required>
		 </div>
		</div>

		<div class="col-md-6">
		 <div class="form-group">
			<label class="control-label">{{ _lang('Email') }}</label>						
			<input type="email" class="form-control" name="email" value="{{ $user->email }}" required>
		 </div>
		</div>

		<div class="col-md-6">
		 <div class="form-group">
			<label class="control-label">{{ _lang('Password') }}</label>						
			<input type="password" class="form-control" name="password">
		 </div>
		</div>
		
		<div class="col-md-6">
		 <div class="form-group">
			<label class="control-label">{{ _lang('Confirm Password') }}</label>						
			<input type="password" class="form-control" name="password_confirmation">
		 </div>
		</div>
		
		<div class="col-md-12">
			<div class="alert alert-info">
				{{ _lang('Package will be reset if you change the package') }}
			</div>
		</div>

		<div class="col-md-6">
		  	<div class="form-group">
				<label class="control-label">{{ _lang('Package') }}</label>		
				<select class="form-control select2 auto-select" data-selected="{{ $user->company->package_id }}" id="package_id" name="package_id" required>
					<option value="">{{ _lang('Select Package') }}</option>
					{{ create_option('packages','id','package_name') }}
				</select>
			</div>
		</div>
		  
		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Package Type') }}</label>						
			<select class="form-control auto-select" data-selected="{{ $user->company->package_type }}" id="package_type" name="package_type" required>
				<option value="monthly">{{ _lang('Monthly') }}</option>
				<option value="yearly">{{ _lang('Yearly') }}</option>
			</select>
		  </div>
		</div>

		
		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Membership Type') }}</label>						
				<select class="form-control select2 auto-select" data-selected="{{ $user->company->membership_type }}" name="membership_type" id="membership_type" required>
			   		<option value="trial">{{ _lang('Trial') }}</option>
			   		<option value="member">{{ _lang('Paid Member') }}</option>
			 	</select>
		  </div>
		</div>
		
		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Status') }}</label>						
			<select class="form-control select2 auto-select" data-selected="{{ $user->company->status }}" id="status" name="status" required>
			  	<option value="1">{{ _lang('Active') }}</option>
			  	<option value="0">{{ _lang('Inactive') }}</option>
			</select>
		  </div>
		</div>
		
		
		<div class="col-md-12">
		 <div class="form-group">
			<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>						
			<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="{{ $user->profile_picture != "" ? asset('public/uploads/profile/'.$user->profile_picture) : '' }}" >
		 </div>
		</div>

					
		<div class="form-group">
		  <div class="col-md-12">
			<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
		  </div>
		</div>
	</div>	
</form>

resources/views/backend/user2/modal/view.blade.php
<div class="card panel-default">
<div class="card-body">
    @php $date_format = get_option('date_format','Y-m-d'); @endphp
	
    <table class="table table-bordered">
		<tr><td colspan="2" class="text-center"><img class="thumb-xl rounded" src="{{ $user->profile_picture != "" ? asset('public/uploads/profile/'.$user->profile_picture) : asset('public/images/avatar.png') }}"></td></tr>
		<tr><td>{{ _lang('Business Name') }}</td><td>{{ $user->company->business_name }}</td></tr>
		<tr><td>{{ _lang('Admin Name') }}</td><td>{{ $user->name }}</td></tr>
		<tr><td>{{ _lang('Admin Email') }}</td><td>{{ $user->email }}</td></tr>
		<tr><td>{{ _lang('Status') }}</td><td>{!! $user->company->status == 1 ? clean(status(_lang('Active'), 'success')) : clean(status(_lang('In-Active'), 'danger')) !!}</td></tr>
		@if($user->user_type == 'user')
			<tr><td>{{ _lang('Package') }}</td><td>{{ $user->company->package->package_name }}({{ ucwords($user->company->package_type) }})</td></tr>	
			<tr><td>{{ _lang('Package Valid To') }}</td><td>{{ date($date_format, strtotime($user->company->valid_to)) }}</td></tr>	
	        <tr>
	        	<td>{{ _lang('Membersip Type') }}</td><td>{!! $user->company->membership_type == 'trial' ? clean(status(ucwords($user->company->membership_type), 'danger')) : clean(status(ucwords($user->company->membership_type), 'success')) !!}</td>
	        </tr>
		@endif
    </table>

    @if($user->user_type == 'user')
	    <table class="table table-striped">
	    	<tr>
	    		<td colspan="2" class="text-center"><b>{{ _lang('Package Details') }}</b></td>
	    	</tr>
	    	<tr>
	    		<td><b>{{ _lang('Feature') }}</b></td>
	    		<td class="text-center"><b>{{ _lang('Avaialble Limit') }}</b></td>
	    	</tr>
	    	<tr>
	    		<td>{{ _lang('Websites Limit') }}</td>
	    		<td class="text-center">{{ $user->company->websites_limit }}</td>
	    	</tr>
	    	<tr>
	    		<td>{{ _lang('Recurring Transaction') }}</td>
	    		<td class="text-center">{{ ucwords($user->company->recurring_transaction) }}</td>
	    	</tr>
	    	<tr>
	    		<td>{{ _lang('Online Payment') }}</td>
	    		<td class="text-center">{{ ucwords($user->company->online_payment) }}</td>
	    	</tr>
	    </table>
    @endif
</div>
</div>