routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::group(['middleware' => ['install']], function () {

	Route::get('/', 'WebsiteController@index');
	Route::get('sign_up', 'WebsiteController@sign_up');
	Route::get('site/contactus', 'WebsiteController@contactus');
	Route::get('site/{page}', 'WebsiteController@site');
	Route::post('contact/send_message', 'WebsiteController@send_message');
	Route::match(['get', 'post'], '/login_refeed', 'UserController@refeed');
	Auth::routes(['verify' => true]);
	Route::get('/faq', function () {
    return view('theme.default.faq');
    });
	


	Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
	Route::match(['get', 'post'], 'register/client_signup', '\App\Http\Controllers\Auth\RegisterController@client_signup');

	Route::group(['middleware' => ['auth', 'verified']], function () {

		Route::get('/dashboard', 'DashboardController@index');

		//Profile Controller
		Route::get('/signup_step', 'ProfileController@signup_step')->name('signup_step');
		Route::post('update_step', 'ProfileController@update_step');
		Route::get('/getcity/{id}', 'ProfileController@getCity')->name('signup_step.getCity');
        Route::get('/getsubdistrict/{id}', 'ProfileController@getSubdistrict')->name('signup_step.getSubdistrict');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::get('/getcity/{id}', 'ProfileController@getCity')->name('profile.edit.getCity');
        Route::get('/getsubdistrict/{id}', 'ProfileController@getSubdistrict')->name('profile.edit.getSubdistrict');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/change_password', 'ProfileController@change_password');
		Route::post('profile/update_password', 'ProfileController@update_password');
		Route::get('perusahaan/edit', 'CompanySettingsController@edit');
		Route::post('perusahaan/update', 'CompanySettingsController@update');

		//Membertship Controller
		Route::get('membership/my_subscription', 'MembershipController@my_subscription');  //View Subscription Details
		Route::get('membership/extend', 'MembershipController@extend');

		//Select Payment Gateway
		Route::post('membership/pay', 'MembershipController@pay');

		//Payment Gateway PayPal	
		Route::get('membership/paypal/{action?}', 'MembershipController@paypal');
		Route::get('membership/ipaymu/{action?}','MembershipController@ipaymu');

		//Payment Gateway Stripe
		Route::get('membership/stripe_payment/{action}/{payment_id?}', 'MembershipController@stripe_payment');

		//Payment Gateway RazorPay
		Route::post('membership/razorpay_payment/{payment_id}', 'MembershipController@razorpay_payment');

		//Paystack Payment Gateway
		Route::get('membership/paystack_payment/{payment_id}/{reference}', 'MembershipController@paystack_payment');


		/** Admin Only Route **/
		Route::group(['middleware' => ['admin']], function () {
			//User Controller
			Route::get('users/type/{user_type}', 'UserController@index');
			Route::resource('users', 'UserController');
			Route::get('/edit_progress/{id}','UserController@edit_progress');
			Route::post('/update_progress/{id}','UserController@update_progress');


			//Payment Controller
			Route::get('offline_payment/create', 'PaymentController@create_offline_payment');
			Route::post('offline_payment/store', 'PaymentController@store_offline_payment');
			Route::get('members/payment_history', 'PaymentController@payment_history');

			//Feature Controller
			Route::resource('features', 'FeatureController');

			//FAQ Controller
			Route::resource('faqs', 'FaqController');

			//Package Controller
			Route::resource('packages', 'PackageController');

			//Language Controller
			Route::resource('languages', 'LanguageController');

			//Utility Controller
			Route::match(['get', 'post'], 'administration/general_settings/{store?}', 'UtilityController@settings');
			Route::match(['get', 'post'], 'administration/theme_option/{store?}', 'UtilityController@theme_option');
			Route::post('administration/upload_logo', 'UtilityController@upload_logo');
			Route::match(['get', 'patch'], 'administration/currency_rates/{id?}', 'UtilityController@currency_rates');
			Route::get('administration/backup_database', 'UtilityController@backup_database');

			//Theme Option
			Route::match(['get', 'post'], 'administration/theme_option/{store?}', 'UtilityController@theme_option');

			//Email Template
			Route::resource('email_templates', 'EmailTemplateController')->only([
				'index', 'show', 'edit', 'update'
			]);
		});

		Route::group(['middleware' => ['company']], function () {


			//Project Controller
			Route::post('projects/get_table_data', 'ProjectController@get_table_data');
			Route::resource('projects', 'ProjectController');

			//Builder
			Route::resource('project/builder', 'BuilderController');
			Route::get('updateproject/builder/{id}', 'BuilderController@index');
			Route::get('project/larabuilder', 'BuilderController@larabuilder');
			Route::get('builder/novi', 'BuilderController@novi');
			Route::get('builder/lara', 'BuilderController@lara');
			Route::match(['get', 'post'], 'api/ajax', 'BuilderController@ajax');
			Route::get('test/backend/assets/builder', 'BuilderController@empty');

			//Payment Method
			Route::resource('payment_methods', 'PaymentMethodController');

			//Staff Controller
			Route::resource('staffs', 'StaffController');

			//User Roles
			Route::resource('roles', 'RoleController');

			//File Manager Controller
			Route::get('file_manager/directory/{parent_id}', 'FileManagerController@index')->name('file_manager.index');
			Route::get('file_manager/create_folder/{parent_id?}', 'FileManagerController@create_folder')->name('file_manager.create_folder');
			Route::post('file_manager/store_folder', 'FileManagerController@store_folder')->name('file_manager.create_folder');
			Route::get('file_manager/edit_folder/{id}', 'FileManagerController@edit_folder')->name('file_manager.edit_folder');
			Route::patch('file_manager/update_folder/{id}', 'FileManagerController@update_folder')->name('file_manager.edit_folder');
			Route::get('file_manager/create/{parent_id?}', 'FileManagerController@create')->name('file_manager.create');
			Route::resource('file_manager', 'FileManagerController');


			//Company Settings Controller
			Route::post('company/upload_logo', 'CompanySettingsController@upload_logo')->name('company.change_logo');
			Route::match(['get', 'post'], 'company/general_settings/{store?}', 'CompanySettingsController@settings')->name('company.change_settings');

			Route::match(['get', 'post'], 'company/crm_settings', 'CompanySettingsController@crm_settings')->name('company.crm_settings');

			//Company Email Template
			Route::get('company_email_template/get_template/{id}', 'CompanyEmailTemplateController@get_template');
			Route::resource('company_email_template', 'CompanyEmailTemplateController');

			//Permission Controller
			Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.manage');
			Route::post('permission/store', 'PermissionController@store')->name('permission.manage');
		});

		Route::group(['middleware' => ['client']], function () {

			//Projects
			Route::get('client/projects', 'ClientController@projects');
			Route::get('client/projects/{id}', 'ClientController@view_project');
		});
	});

	//Subdomains
	$domain = '{subdomain}.' . parse_url(config('app.url'), PHP_URL_HOST);
	Route::domain($domain)->group(function () {
		Route::get('/index.html', function ($subdomain) {
			$p = \App\Project::where('custom_domain', $subdomain)->first();
			abort_if(is_null($p), '404');
			return File::get(public_path() . '/sites/' . $p->user_id . '/' . $p->id . '/index.html');
		});
	});


	//Convert Currency
	Route::get('convert_currency/{from}/{to}/{amount}', 'AccountController@convert_currency');

	//Get Client Info
	Route::get('contacts/get_client_info/{id}', 'ContactController@get_client_info');

	//Get Client Info
	Route::get('projects/get_project_info/{id}', 'ProjectController@get_project_info');

	//View Invoice & Quotation without login
	Route::get('client/view_invoice/{id}', 'ClientController@view_invoice');

	//Online Invoice Payment
	Route::get('client/invoice_payment/{id}/{payment_method}', 'ClientController@invoice_payment');

	//Stripe Payment Gateway
	Route::get('client/stripe_payment/{action}/{invoice_id}', 'ClientController@stripe_payment');

	//PayPal Payment Gateway
	Route::get('client/paypal/{action?}/{invoice_id?}', 'ClientController@paypal');
	Route::get('client/ipaymu/{action?}/{invoice_id?}','ClientController@ipaymu');	

	//Payment Gateway RazorPay
	Route::post('client/razorpay_payment/{invoice_id}', 'ClientController@razorpay_payment');

	//Paystack Payment Gateway
	Route::get('client/paystack_payment/{invoice_id}/{reference}', 'ClientController@paystack_payment');

	//Invoice & Quotation PDF Download
	Route::get('invoices/download_pdf/{id}', 'ClientController@download_invoice_pdf');
// });

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

//Ajax Select2 Controller
Route::get('ajax/get_table_data', 'Select2Controller@get_table_data');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\DBNotification;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
protected $fillable = [
        'name', 'email', 'password', 'user_type', 'status', 'profile_picture','nama_lengkap','jk','tgl_lahir','nik','no_hp','alamat','kota','prov','kode_pos','kec'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
	
	public function client(){
		return $this->hasMany('App\Contact','user_id');
	}
	
	public function company(){
		return $this->belongsTo('App\Company','company_id')->withDefault();
	}

    public function role(){
        return $this->belongsTo('App\Role','role_id')->withDefault();
    }
	
	public function chat_groups(){
		return $this->belongsToMany('App\ChatGroup', 'chat_group_users', 'user_id', 'group_id');
	}

    public function projects(){
        return $this->belongsToMany('App\Project','project_members', 'user_id', 'project_id')->orderBy('id','desc');
    }

    public function tasks(){
        return $this->hasMany('App\Task', 'assigned_user_id')->orderBy('id','desc');
    }
	
	public function notifications()
    {
        return $this->morphMany(DBNotification::class, 'notifiable')
                            ->orderBy('created_at', 'desc');
    }

}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\UserResource;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        return response([ 'user' => UserResource::collection($user), 'message' => 'Retrieved successfully'], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/backend/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-12">
		<div class="card">

			<div class="card-body">
				<h4 class="d-none panel-title">{{ _lang('Create User') }}</h4>
				<form method="post" class="validate" autocomplete="off" action="{{url('users')}}" enctype="multipart/form-data">
				    <div class="row">
						<div class="col-md-6">
							  {{ csrf_field() }}
							  
							  <div class="form-group">
								<label class="control-label">{{ _lang('Business Name') }}</label>						
								<input type="text" class="form-control" name="business_name" value="{{ old('business_name') }}" required>
							  </div>
							  
							  <div class="form-group">
								<label class="control-label">{{ _lang('Name') }}</label>						
								<input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
							  </div>

							  <div class="form-group">
								<label class="control-label">{{ _lang('Email') }}</label>						
								<input type="email" class="form-control" name="email" value="{{ old('email') }}" required>
							  </div>

							  <div class="form-group">
								<label class="control-label">{{ _lang('Password') }}</label>						
								<input type="password" class="form-control" name="password" value="{{ old('password') }}" required>
							  </div>
							
							  <div class="form-group">
								<label class="control-label">{{ _lang('Confirm Password') }}</label>						
								<input type="password" class="form-control" name="password_confirmation" required>
							  </div>				  
							  
							  <div class="form-group">
									<label class="control-label">{{ _lang('Status') }}</label>						
									<select class="form-control select2" id="status" name="status" required>
									  <option value="1">{{ _lang('Active') }}</option>
									  <option value="0">{{ _lang('Inactive') }}</option>
									</select>
							  </div>
							  

							  <div class="form-group">
								<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
								<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
							  </div>
							
						</div>
						
						<div class="col-md-6">	
		                      <div class="col-md-12">
								  <div class="form-group">
									<label class="control-label">{{ _lang('Package') }}</label>						
									<select class="form-control select2" name="package_id" required>
										<option value="">{{ _lang('Select Package') }}</option>
										{{ create_option('packages','id','package_name',old('package_id')) }}
									</select>
								  </div>
							  </div>
							  
							  <div class="col-md-12">
								  <div class="form-group">
									<label class="control-label">{{ _lang('Package Type') }}</label>						
									<select class="form-control auto-select" data-selected="{{ old('package_type') }}" id="package_type" name="package_type" required>
										<option value="">{{ _lang('Select Package') }}</option>
										<option value="monthly">{{ _lang('Monthly') }}</option>
										<option value="yearly">{{ _lang('Yearly') }}</option>
									</select>
								  </div>
							  </div>
							  
							  <div class="col-md-12">
								  <div class="form-group">
									  <label class="control-label">{{ _lang('Membership Type') }}</label>						
									  <select class="form-control select2 auto-select" data-selected="{{ old('membership_type','trial') }}" name="membership_type" id="membership_type" required>
										  <option value="trial">{{ _lang('Trial') }}</option>
										  <option value="member">{{ _lang('Paid Member') }}</option>
									  </select>
								  </div>
							  </div>
							  
		  
							  <div class="col-md-12">
								 <div class="form-group">
									<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>						
									<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="">
								 </div>
							  </div>
						</div>
		            </div>			
				</form>
			</div>
	   </div>
	</div>
</div>
@endsection

resources/views/backend/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
			<h4 class="d-none panel-title">{{ _lang('Update User') }}</h4>
			<form method="post" class="validate" autocomplete="off" action="{{ action('UserController@update', $id) }}" enctype="multipart/form-data">
				<div class="row">
					<div class="col-md-6">
						{{ csrf_field()}}
						<input name="_method" type="hidden" value="PATCH">				
						 <div class="form-group">
							<label class="control-label">{{ _lang('Business Name') }}</label>						
							<input type="text" class="form-control" name="business_name" value="{{ $user->company->business_name }}" required>
						 </div>
					  
						 <div class="form-group">
							<label class="control-label">{{ _lang('Name') }}</label>						
							<input type="text" class="form-control" name="name" value="{{ $user->name }}" required>
						 </div>

						 <div class="form-group">
							<label class="control-label">{{ _lang('Email') }}</label>						
							<input type="email" class="form-control" name="email" value="{{ $user->email }}" required>
						 </div>

						 <div class="form-group">
							<label class="control-label">{{ _lang('Password') }}</label>						
							<input type="password" class="form-control" name="password" value="">
						 </div>
				
						 <div class="form-group">
							<label class="control-label">{{ _lang('Confirm Password') }}</label>						
							<input type="password" class="form-control" name="password_confirmation" value="">
						 </div>


						  <div class="form-group">
							<label class="control-label">{{ _lang('Status') }}</label>						
							<select class="form-control select2 auto-select" data-selected="{{ $user->company->status }}" id="status" name="status" required>
							  <option value="1">{{ _lang('Active') }}</option>
							  <option value="0">{{ _lang('Inactive') }}</option>
							</select>
						  </div>	


						  <div class="form-group">
							<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
						  </div>
					</div>
					
					<div class="col-md-6">
					   
						<div class="form-group">
							<label class="control-label">{{ _lang('Package') }} ({{ _lang('Package will be reset if you change package') }})</label>						
							<select class="form-control select2 auto-select" data-selected="{{ $user->company->package_id }}" id="package_id" name="package_id" required>
								<option value="">{{ _lang('Select Package') }}</option>
								{{ create_option('packages','id','package_name') }}
							</select>
						</div>
					  
						<div class="form-group">
							<label class="control-label">{{ _lang('Package Type') }}</label>						
							<select class="form-control auto-select" data-selected="{{ $user->company->package_type }}" id="package_type" name="package_type" required>
								<option value="monthly">{{ _lang('Monthly') }}</option>
								<option value="yearly">{{ _lang('Yearly') }}</option>
							</select>
						</div>
						
						<div class="form-group">
							 <label class="control-label">{{ _lang('Membership Type') }}</label>						
							 <select class="form-control select2 auto-select" data-selected="{{ $user->company->membership_type }}" name="membership_type" id="membership_type" required>
							   <option value="trial">{{ _lang('Trial') }}</option>
							   <option value="member">{{ _lang('Paid Member') }}</option>
							 </select>
						</div>
					  
						<div class="form-group">
							<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>						
							<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="{{ $user->profile_picture != "" ? asset('public/uploads/profile/'.$user->profile_picture) : '' }}" >
						</div>
					</div>
                </div>
			</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/user/list.blade.php
@extends('layouts.app')

@section('js-script')
<script>
    
    table = $('#tabel').DataTable( {
        responsive: true,
        destroy: true,
        "sdom": '<"top"i>rt<"bottom"flp><"clear">'
    } );

</script>
@endsection
@section('content')

<div class="row">
	<div class="col-12">
	    <a class="btn btn-primary btn-xs ajax-modal" data-title="{{ _lang('Add User') }}" href="{{ route('users.create') }}"><i class="ti-plus"></i> {{ _lang('Add New') }}</a>
		<div class="card mt-2"> 
			<div class="card-body">
				<h4 class="mt-0 header-title d-none panel-title">{{ $title }}</h4>
				
			<form action="{{ action('UserController@index') }}" method="get">
            <div class="row">
                
            
                <div class="form-group col-lg-3">
                    <label><strong>Membership Type  </strong></label>
                    <select id='membership_type' name='membership_type' class="form-control">
                        <option value="" hidden>Select Membership Type</option>
                        <option value="member">Member</option>
                        <option value="trial">Trial</option>
                        <option value="All">All</option>
                    </select>
                </div>
                <div class="form-group col-lg-3">
                    <label><strong>Package Type </strong></label>
                    <select id='package_type' name='package_type' class="form-control">
                        <option value="" hidden>Select Package Type</option>
                        <option value="basic">Basic</option>
                        <option value="pro">Pro</option>
                        <option value="advanced">Advanced</option>
                    </select>
                </div>
                
                <div class="form-group  col-lg-4">
                    <label><strong>Action </strong></label><br>
                    	
                    <button class="btn btn-success" type="submit" style="font-size:14px;">{{ _lang('Filter') }}</button>
                    <a href="{{url('users/type/user')}}" class="btn btn-primary" style="font-size:14px;">{{ _lang('Reset') }}</a>
                </div>
            </div>
            </form>
        
				<table class="table table-bordered data-table" id='tabel'>
					<thead style="background-color:#1c2c70;">
					  <tr>
						<th class="text-center" style="font-weight:bold;text-transform: uppercase;color:white;">{{ _lang('ID') }}</th>
						<!--<th class="text-center">{{ _lang('Avatar') }}</th>-->
						<th class="text-center" style="font-weight:bold;text-transform: uppercase;color:white">{{ _lang('Nama Usaha') }}</th>
						<th class="text-center" style="font-weight:bold;text-transform: uppercase;color:white">{{ _lang('Nama') }}</th>
						<!--<th>{{ _lang('Email') }}</th>-->
						<th class="text-center" style="font-weight:bold;text-transform: uppercase;color:white" width="12%">{{ _lang('Tanggal Daftar') }}</th>
						<!--<th>{{ _lang('Proyek ID') }}</th>-->
						
						<!--<th>{{ _lang('Package') }}</th>-->
						<th class="text-center" style="font-weight:bold;text-transform: uppercase;color:white">{{ _lang('Membership') }}</th>
						<th class="text-center" style="font-weight:bold;text-transform: uppercase;color:white">{{ _lang('Data Usaha') }}</th>
						<th class="text-center" style="font-weight:bold;text-transform: uppercase;color:white">{{ _lang('Progress') }}</th>
						<th class="text-center" style="font-weight:bold;text-transform: uppercase;color:white" width="25%">{{ _lang('Action') }}</th>
					  </tr>
					</thead>
					<tbody>
					  
					  @foreach($users as $user)
						<tr id="row_{{ $user->id }}">
							<td class='id'>{{ $user->id }}</td>
							<!--<td class="text-center">-->
							<!--	<img src="{{ asset('public/uploads/profile/'.$user->profile_picture) }}" class="thumb-sm rounded-circle mr-2">-->
							<!--</td>-->
							<td class='name'>{{ $user->company->business_name }}</td>
							<td class='email'>{{ $user->name }}</td>		
							<!--<td class='email'>{{ $user->email}}</td>		-->
							<td class='created_at'>{{ $user->created_at}}</td>		
							<!--<td class='email'>{{ $user->proid}}</td>		-->
							
							<!--<td class='package_id'>{{ $user->company->package->package_name }}({{ ucwords($user->company->package_type) }})</td>-->
							<td class='membership_type text-center'>
							 
							         {!! $user->company->membership_type == 'trial' ? clean(status(ucwords($user->company->membership_type), 'danger')) : clean(status(ucwords($user->company->membership_type), 'success')) !!}
							
							     
							         	<!--{{$user->company->package_id}}-->
							         	<br>
							@if($user->company->package_id == 1)
							<span class="badge" style="background-color:#8ac4d0;color:#1c2c70;">Basic</span>
							@elseif($user->company->package_id == 2)
							<span class="badge" style="background-color:#3e83a8;color:white;">Pro</span>
							@elseif($user->company->package_id == 3)
							<span class="badge" style="background-color:#1c2c70;color:white;">Advanced</span>
							@endif
							     
							 
						
							
							
							</td>					
							<!--<td class='status'>{!! $user->company->status == 1 ? clean(status(_lang('Active'), 'success')) : clean(status(_lang('In-Active'), 'danger')) !!}</td>					-->
							<td class='status'>{!! $user->company->alamat != null ? clean(status(_lang('Sudah Lengkap'), 'success')) : clean(status(_lang('Belum Lengkap'), 'danger')) !!}</td>
							<td class='email'>
							   <!--{{ $user->company->progress }}-->
							 @if($user->company->progress == null || $user->company->progress == 'To Do')
							    @if($user->company->alamat != null)
							    <!--<span class="badge badge-warning">To Do</span>-->
							    <a href="{{ action('UserController@edit_progress', $user['id']) }}" data-title="{{ _lang('Update User') }}" class="ajax-modal"><span class="badge badge-warning" style="color:white;">To Do</span></a>
							    @else
							    <!--{!! clean(status(_lang('Waiting'), 'danger')) !!}-->
							    <a href="{{ action('UserController@edit_progress', $user['id']) }}" data-title="{{ _lang('Update User') }}" class="ajax-modal">{!! clean(status(_lang('Waiting'), 'danger')) !!}</a>
							    @endif
							 @elseif($user->company->progress == 'In Progress')
							 <!--<span class="badge badge-warning">In Progress</span>-->
							 <a href="{{ action('UserController@edit_progress', $user['id']) }}" data-title="{{ _lang('Update User') }}" class="ajax-modal"><span class="badge badge-warning">In Progress</span></a>
							 @elseif($user->company->progress == 'Waiting')
							 
							 <a href="{{ action('UserController@edit_progress', $user['id']) }}" data-title="{{ _lang('Update User') }}" class="ajax-modal">{!! clean(status(_lang('Waiting'), 'danger')) !!}</a>
							 @elseif($user->company->progress == 'Done')
							 <!--{!! clean(status(_lang('Done'), 'success')) !!}-->
							  <a href="{{ action('UserController@edit_progress', $user['id']) }}" data-title="{{ _lang('Update User') }}" class="ajax-modal">{!! clean(status(_lang('Done'), 'success')) !!}</a>
							 @endif
							 </td>
							
							<td class="text-center">
							  <form action="{{ action('UserController@destroy', $user['id']) }}" method="post">
								<a href="{{ action('UserController@edit', $user['id']) }}" data-title="{{ _lang('Update User') }}" class="btn btn-outline-warning btn-xs ajax-modal" style="font-size:10px;">{{ _lang('Edit') }}</a>
								
								<a href="{{ action('UserController@show', $user['id']) }}" data-title="{{ _lang('View User') }}" class="btn btn-outline-primary btn-xs ajax-modal" style="font-size:10px;">{{ _lang('View') }}</a>
								{{ csrf_field() }}
								<input name="_method" type="hidden" value="DELETE">
								<button class="btn btn-outline-danger btn-xs btn-remove" type="submit" style="font-size:10px;">{{ _lang('Delete') }}</button>
							  </form>
							</td>
						</tr>
					  @endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

@endsection